---
# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.2.1
_src_path: gh:radio-aktywne/template-devcontainer
accountname: radio-aktywne
description: Devcontainer for Litestar apps 🌠
devcontainername: app-litestar
docs: true
docsurl: https://radio-aktywne.github.io/devcontainer-app-litestar
imagename: devcontainers/app-litestar
registry: true
releases: true
reponame: devcontainer-app-litestar
repourl: https://github.com/radio-aktywne/devcontainer-app-litestar
